name: Update Commit Timestamp

on:
  push:
    branches:
      - main

jobs:
  update-commit-timestamp:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Extract Commit Timestamp
        run: echo "COMMIT_TIMESTAMP=$(git log -1 --format=%ci)" >> $GITHUB_ENV